'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17379
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Vifarnet_Xplr_.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property admin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("admin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property akon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("akon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Alert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bar12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bar12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bar121() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bar121", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bar1b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bar1b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bar1b1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bar1b1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bar22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bar22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bar3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bar3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg71() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg71", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg81() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg81", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property border() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property breakingdawn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breakingdawn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bubbles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bubbles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calc1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calc1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property desc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dj() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dj", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dj_dis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dj_dis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dj1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dj1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Earth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Earth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eclipse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eclipse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eminem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eminem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enig2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enig2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fixit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fixit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fixit_dis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fixit_dis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property form() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("form", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gmail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gmail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property google() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("google", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help1_dis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help1_dis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property infoy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("infoy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property internet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("internet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property js() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("js", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property live() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("live", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property load() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("load", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property load1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("load1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property load13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("load13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property load15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("load15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property load17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("load17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property load2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("load2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property load20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("load20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property load4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("load4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property load7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("load7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lock1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property math() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("math", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property math1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("math1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property math3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("math3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property math3_dis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("math3_dis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property math4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("math4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property math5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("math5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property math6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("math6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mi1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mi1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mi2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mi2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mi3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mi3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mi4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mi4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mov1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mov1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mov1_dis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mov1_dis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mov2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mov2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mov3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mov3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property music() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("music", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property newmoon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newmoon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property note1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property note2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OK1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OK1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OK2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OK2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property open1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pi_Math() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pi-Math", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rediff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rediff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh_dis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh_dis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property restart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rfsh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rfsh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settings_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settings_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settings_51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Software_update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Software-update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Software_update1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Software-update1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sp_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sp+", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splshscrn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splshscrn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property srch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("srch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property srch_adv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("srch_adv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property srch_adv1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("srch_adv1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property srch_adv11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("srch_adv11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property task() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("task", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property taskx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taskx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property twilight2008() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twilight2008", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property uninst() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uninst", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property update1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property window() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property window1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Xemplar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Xemplar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Xemplar_dis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Xemplar_dis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property xp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property xp1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xp1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property xplore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xplore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property xplore_dis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xplore_dis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property xplr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xplr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
